### ISSUE TITLE
Ui bug when window is narrow

### ISSUE THREAD

**Issue by don-tay** [AY1920S2-CS2103T-T10-4/main#271]
Screenshot below is UI for 10 modules. I think we should set a `minWidth` for the module card, and allow scrolling of the cards
<img width="795" alt="Screenshot 2020-04-11 at 4 57 18 AM" src="https://user-images.githubusercontent.com/21982878/79022665-103bbe00-7bb1-11ea-8915-1c31e5116871.png">

<img width="1136" alt="Screenshot 2020-04-11 at 4 57 15 AM" src="https://user-images.githubusercontent.com/21982878/79022656-0ade7380-7bb1-11ea-9a21-91952873afad.png">

**Comment by CharmaineKoh** [comment]
I will just hard code the width.
