### ISSUE TITLE
Suggestions/Comments for DG

### ISSUE THREAD

**Issue by Tejas2805** [AY1920S2-CS2103T-T10-4/main#276]
Suggestions/Comments for DG:

1. Lot of AddressBook there. Delete them. Refactor them.
2. Don't repeat diagrams. Logic manager for example.
3. CD for Reminder features - Why so big? Need to scroll down or zoom out to see full image at once. Try to reduce its size, if possible.
4. Sequence Diagram for Automation adds no value - It's so small, can't read anything. Need to zoom in a lot. Please refactor them into smaller compact diagrams. 
5. Activity Diagram for Automation is wrong. 
6. Remove Product Survey. Add stuff to Glossary.
7. Some diagrams have background colors. Some don't. Maintain consistency. Decide how you want to proceed. 
8. Use cases can be made better. Do refer to T10-3 for examples. They have good ones.

**Comment by kester-ng** [comment]
Thank you for the suggestions, will update the DG accordingly. Thank you!! :>
